# Site settings
course_name: CE310 Transportation Engineering I
# course_description: "This course is designed to provide the student with tools and methods to analyze, design and plan airport and railway infrastructure."
course_semester: "Atumun 2020"

baseurl: #"/ce310" # the subpath of your site, e.g. /blog/
url: "" #"http://catchpriyansh.github.io/" # the base hostname & protocol for your site

schoolname: "Department of Civil Engineering, IIT Indore"
schoolurl: "https://priyanshsingh.com"
twitter_username: catchpriyansh 

address: |
    Dr. Priyansh Singh
    311 POD 1D Department of Civil Engineering
    IIT Indore, Simrol (M.P.)
    

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
google_analytics: UA-176001582-1

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"

github: [metadata]
